use crate::error::{NetcidrError, Result};
use serde::Deserialize;
use std::net::IpAddr;

const MAX_BATCH_SIZE_LIMIT: usize = 100_000;
const MAX_GENERATED_CIDRS_LIMIT: usize = 1_000_000;
const MAX_SUMMARIZE_INPUTS_LIMIT: usize = 100_000;
const MAX_BODY_SIZE_LIMIT: usize = 10_485_760; // 10 MiB
const MAX_RATE_LIMIT_PER_SECOND: u64 = 10_000;
const MAX_RATE_LIMIT_BURST: u32 = 100_000;
const MAX_TIMEOUT_SECONDS: u64 = 300;
const AUTH_TOKEN_ENV: &str = "NETCIDR_API_TOKEN";

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ServerConfig {
    /// Maximum CIDRs in a single batch request
    pub max_batch_size: usize,
    /// Maximum CIDRs generated by from-range
    pub max_generated_cidrs: usize,
    /// Maximum input CIDRs for summarize
    pub max_summarize_inputs: usize,
    /// Maximum request body size in bytes
    pub max_body_size: usize,
    /// Rate limit: sustained requests per second
    pub rate_limit_per_second: u64,
    /// Rate limit: burst size
    pub rate_limit_burst: u32,
    /// Request timeout in seconds
    pub timeout_seconds: u64,
    /// Enable Swagger UI
    pub enable_swagger: bool,
    /// Enable IPAM API routes
    pub ipam_enabled: bool,
    /// IPAM storage backend ("sqlite" or "postgres")
    pub ipam_backend: String,
    /// IPAM database path (SQLite)
    pub ipam_db: Option<String>,
    /// IPAM database URL (PostgreSQL)
    pub ipam_db_url: Option<String>,
    /// Bearer token for HTTP API authentication. Prefer NETCIDR_API_TOKEN in production.
    pub auth_token: Option<String>,
    /// Allow binding the HTTP API to a non-loopback address.
    pub allow_public_bind: bool,
    /// Require authentication when binding the HTTP API to a non-loopback address.
    pub require_auth_for_public_bind: bool,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            max_batch_size: 10_000,
            max_generated_cidrs: 1_000_000,
            max_summarize_inputs: 10_000,
            max_body_size: 1_048_576, // 1 MB
            rate_limit_per_second: 20,
            rate_limit_burst: 50,
            timeout_seconds: 30,
            enable_swagger: false,
            ipam_enabled: false,
            ipam_backend: "sqlite".to_string(),
            ipam_db: None,
            ipam_db_url: None,
            auth_token: None,
            allow_public_bind: false,
            require_auth_for_public_bind: true,
        }
    }
}

#[derive(Debug, Default)]
pub struct CliOverrides {
    pub enable_swagger: bool,
    pub max_batch_size: Option<usize>,
    pub max_range_cidrs: Option<usize>,
    pub max_summarize_inputs: Option<usize>,
    pub max_body_size: Option<usize>,
    pub rate_limit_per_second: Option<u64>,
    pub rate_limit_burst: Option<u32>,
    pub timeout: Option<u64>,
    pub ipam_enabled: bool,
    pub ipam_backend: Option<String>,
    pub ipam_db: Option<String>,
    pub ipam_db_url: Option<String>,
}

impl ServerConfig {
    pub fn load(path: &str) -> Result<Self> {
        // nosemgrep: rust.actix.path-traversal.tainted-path.tainted-path — CLI-only startup config, not reachable from HTTP input
        let contents = std::fs::read_to_string(path)?;
        let config: ServerConfig =
            toml::from_str(&contents).map_err(|e| NetcidrError::ConfigParse(e.to_string()))?;
        config.validate()?;
        Ok(config)
    }

    pub fn merge_cli_overrides(&mut self, overrides: &CliOverrides) {
        if overrides.enable_swagger {
            self.enable_swagger = true;
        }
        if let Some(v) = overrides.max_batch_size {
            self.max_batch_size = v;
        }
        if let Some(v) = overrides.max_range_cidrs {
            self.max_generated_cidrs = v;
        }
        if let Some(v) = overrides.max_summarize_inputs {
            self.max_summarize_inputs = v;
        }
        if let Some(v) = overrides.max_body_size {
            self.max_body_size = v;
        }
        if let Some(v) = overrides.rate_limit_per_second {
            self.rate_limit_per_second = v;
        }
        if let Some(v) = overrides.rate_limit_burst {
            self.rate_limit_burst = v;
        }
        if let Some(v) = overrides.timeout {
            self.timeout_seconds = v;
        }
        if overrides.ipam_enabled {
            self.ipam_enabled = true;
        }
        if let Some(ref v) = overrides.ipam_backend {
            self.ipam_backend = v.clone();
        }
        if overrides.ipam_db.is_some() {
            self.ipam_db.clone_from(&overrides.ipam_db);
        }
        if overrides.ipam_db_url.is_some() {
            self.ipam_db_url.clone_from(&overrides.ipam_db_url);
        }
    }

    pub fn validate(&self) -> Result<()> {
        validate_range_usize("max_batch_size", self.max_batch_size, 1, MAX_BATCH_SIZE_LIMIT)?;
        validate_range_usize(
            "max_generated_cidrs",
            self.max_generated_cidrs,
            1,
            MAX_GENERATED_CIDRS_LIMIT,
        )?;
        validate_range_usize(
            "max_summarize_inputs",
            self.max_summarize_inputs,
            1,
            MAX_SUMMARIZE_INPUTS_LIMIT,
        )?;
        validate_range_usize("max_body_size", self.max_body_size, 1, MAX_BODY_SIZE_LIMIT)?;
        validate_range_u64(
            "rate_limit_per_second",
            self.rate_limit_per_second,
            1,
            MAX_RATE_LIMIT_PER_SECOND,
        )?;
        validate_range_u32(
            "rate_limit_burst",
            self.rate_limit_burst,
            1,
            MAX_RATE_LIMIT_BURST,
        )?;
        validate_range_u64("timeout_seconds", self.timeout_seconds, 1, MAX_TIMEOUT_SECONDS)?;

        if self
            .auth_token
            .as_ref()
            .is_some_and(|token| token.trim().is_empty())
        {
            return Err(NetcidrError::InvalidInput(
                "auth_token must not be empty".to_string(),
            ));
        }

        match self.ipam_backend.as_str() {
            "sqlite" | "postgres" => Ok(()),
            other => Err(NetcidrError::InvalidInput(format!(
                "ipam_backend must be 'sqlite' or 'postgres' (got '{other}')"
            ))),
        }
    }

    pub fn auth_token(&self) -> Option<String> {
        std::env::var(AUTH_TOKEN_ENV)
            .ok()
            .filter(|token| !token.trim().is_empty())
            .or_else(|| {
                self.auth_token
                    .clone()
                    .filter(|token| !token.trim().is_empty())
            })
    }

    pub fn auth_configured(&self) -> bool {
        self.auth_token().is_some()
    }

    pub fn validate_deployment(&self, bind_address: &str) -> Result<()> {
        self.validate()?;

        let is_loopback = is_loopback_bind_address(bind_address)?;
        if !is_loopback {
            if !self.allow_public_bind {
                return Err(NetcidrError::InvalidInput(format!(
                    "refusing to bind to non-loopback address '{bind_address}' unless allow_public_bind=true"
                )));
            }
            if self.require_auth_for_public_bind && !self.auth_configured() {
                return Err(NetcidrError::InvalidInput(format!(
                    "refusing to bind to non-loopback address '{bind_address}' without authentication; set {AUTH_TOKEN_ENV} or auth_token"
                )));
            }
        }

        if self.ipam_enabled && !self.auth_configured() {
            return Err(NetcidrError::InvalidInput(format!(
                "IPAM API requires authentication; set {AUTH_TOKEN_ENV} or auth_token"
            )));
        }

        Ok(())
    }
}

fn is_loopback_bind_address(bind_address: &str) -> Result<bool> {
    let trimmed = bind_address.trim();
    let host = trimmed
        .strip_prefix('[')
        .and_then(|s| s.strip_suffix(']'))
        .unwrap_or(trimmed);

    let ip: IpAddr = host.parse().map_err(|_| {
        NetcidrError::InvalidInput(format!("invalid bind address '{bind_address}'"))
    })?;
    Ok(ip.is_loopback())
}

fn validate_range_usize(name: &str, value: usize, min: usize, max: usize) -> Result<()> {
    if value < min || value > max {
        return Err(NetcidrError::InvalidInput(format!(
            "{name} must be between {min} and {max} (got {value})"
        )));
    }
    Ok(())
}

fn validate_range_u64(name: &str, value: u64, min: u64, max: u64) -> Result<()> {
    if value < min || value > max {
        return Err(NetcidrError::InvalidInput(format!(
            "{name} must be between {min} and {max} (got {value})"
        )));
    }
    Ok(())
}

fn validate_range_u32(name: &str, value: u32, min: u32, max: u32) -> Result<()> {
    if value < min || value > max {
        return Err(NetcidrError::InvalidInput(format!(
            "{name} must be between {min} and {max} (got {value})"
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = ServerConfig::default();
        assert_eq!(config.max_batch_size, 10_000);
        assert_eq!(config.max_generated_cidrs, 1_000_000);
        assert_eq!(config.max_summarize_inputs, 10_000);
        assert_eq!(config.max_body_size, 1_048_576);
        assert_eq!(config.rate_limit_per_second, 20);
        assert_eq!(config.rate_limit_burst, 50);
        assert_eq!(config.timeout_seconds, 30);
        assert!(!config.enable_swagger);
        assert!(!config.allow_public_bind);
        assert!(config.require_auth_for_public_bind);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_merge_cli_overrides() {
        let mut config = ServerConfig::default();
        config.merge_cli_overrides(&CliOverrides {
            enable_swagger: true,
            max_batch_size: Some(500),
            timeout: Some(60),
            ..Default::default()
        });
        assert!(config.enable_swagger);
        assert_eq!(config.max_batch_size, 500);
        assert_eq!(config.max_generated_cidrs, 1_000_000); // unchanged
        assert_eq!(config.timeout_seconds, 60);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_toml_deserialization() {
        let toml_str = r#"
            max_batch_size = 500
            enable_swagger = true
            auth_token = "test-token"
            allow_public_bind = true
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert_eq!(config.max_batch_size, 500);
        assert!(config.enable_swagger);
        assert_eq!(config.auth_token.as_deref(), Some("test-token"));
        assert!(config.allow_public_bind);
        // defaults for unspecified fields
        assert_eq!(config.max_generated_cidrs, 1_000_000);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_invalid_toml_syntax_returns_config_parse_error() {
        let bad_toml = r#"max_batch_size = "not a number"#; // unclosed quote
        let result = toml::from_str::<ServerConfig>(bad_toml);
        assert!(result.is_err());
    }

    #[test]
    fn test_malformed_toml_missing_value() {
        let bad_toml = "max_batch_size = ";
        let result = toml::from_str::<ServerConfig>(bad_toml);
        assert!(result.is_err());
    }

    #[test]
    fn test_wrong_type_for_field() {
        let bad_toml = r#"max_batch_size = "hello""#;
        let result = toml::from_str::<ServerConfig>(bad_toml);
        assert!(result.is_err(), "string value for usize field should fail");
    }

    #[test]
    fn test_negative_value_for_unsigned_field() {
        let bad_toml = "timeout_seconds = -1";
        let result = toml::from_str::<ServerConfig>(bad_toml);
        assert!(result.is_err(), "negative value for u64 field should fail");
    }

    #[test]
    fn test_unknown_fields_are_rejected() {
        let toml_str = r#"
            max_batch_size = 42
            totally_fake_field = "hello"
        "#;
        let result = toml::from_str::<ServerConfig>(toml_str);
        assert!(result.is_err(), "unknown config fields should fail closed");
    }

    #[test]
    fn test_partial_config_fills_defaults() {
        let toml_str = r#"
            enable_swagger = true
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert!(config.enable_swagger);
        assert_eq!(config.max_batch_size, 10_000);
        assert_eq!(config.max_generated_cidrs, 1_000_000);
        assert_eq!(config.max_summarize_inputs, 10_000);
        assert_eq!(config.max_body_size, 1_048_576);
        assert_eq!(config.rate_limit_per_second, 20);
        assert_eq!(config.rate_limit_burst, 50);
        assert_eq!(config.timeout_seconds, 30);
        assert!(!config.ipam_enabled);
        assert_eq!(config.ipam_backend, "sqlite");
        assert!(config.ipam_db.is_none());
        assert!(config.auth_token.is_none());
        assert!(!config.allow_public_bind);
        assert!(config.require_auth_for_public_bind);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_empty_toml_yields_all_defaults() {
        let config: ServerConfig = toml::from_str("").unwrap();
        let defaults = ServerConfig::default();
        assert_eq!(config.max_batch_size, defaults.max_batch_size);
        assert_eq!(config.timeout_seconds, defaults.timeout_seconds);
        assert_eq!(config.enable_swagger, defaults.enable_swagger);
        assert_eq!(config.ipam_backend, defaults.ipam_backend);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_boundary_values_zero_are_rejected_by_validation() {
        let toml_str = r#"
            max_batch_size = 0
            timeout_seconds = 0
            rate_limit_per_second = 0
            rate_limit_burst = 0
            max_body_size = 0
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_boundary_value_large_numbers_are_rejected_by_validation() {
        let toml_str = r#"
            max_batch_size = 18446744073709551615
            timeout_seconds = 18446744073709551615
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_invalid_ipam_backend_is_rejected() {
        let mut config = ServerConfig::default();
        config.ipam_backend = "mysql".to_string();
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_empty_auth_token_is_rejected() {
        let mut config = ServerConfig::default();
        config.auth_token = Some("   ".to_string());
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_validate_deployment_allows_loopback_without_auth() {
        let config = ServerConfig::default();
        assert!(config.validate_deployment("127.0.0.1").is_ok());
        assert!(config.validate_deployment("::1").is_ok());
        assert!(config.validate_deployment("[::1]").is_ok());
    }

    #[test]
    fn test_validate_deployment_rejects_public_bind_without_opt_in() {
        let mut config = ServerConfig::default();
        config.auth_token = Some("test-token".to_string());
        assert!(config.validate_deployment("0.0.0.0").is_err());
    }

    #[test]
    fn test_validate_deployment_rejects_public_bind_without_auth() {
        let config = ServerConfig {
            allow_public_bind: true,
            ..Default::default()
        };
        assert!(config.validate_deployment("0.0.0.0").is_err());
    }

    #[test]
    fn test_validate_deployment_allows_public_bind_with_auth_and_opt_in() {
        let config = ServerConfig {
            allow_public_bind: true,
            auth_token: Some("test-token".to_string()),
            ..Default::default()
        };
        assert!(config.validate_deployment("0.0.0.0").is_ok());
    }

    #[test]
    fn test_validate_deployment_rejects_ipam_without_auth() {
        let config = ServerConfig {
            ipam_enabled: true,
            ..Default::default()
        };
        assert!(config.validate_deployment("127.0.0.1").is_err());
    }

    #[test]
    fn test_validate_deployment_allows_ipam_with_auth() {
        let config = ServerConfig {
            ipam_enabled: true,
            auth_token: Some("test-token".to_string()),
            ..Default::default()
        };
        assert!(config.validate_deployment("127.0.0.1").is_ok());
    }

    #[test]
    fn test_load_nonexistent_file_returns_io_error() {
        let result = ServerConfig::load("/tmp/nonexistent_netcidr_config_test.toml");
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            matches!(err, NetcidrError::Io(_)),
            "expected Io error, got: {err:?}"
        );
    }

    #[test]
    fn test_load_invalid_toml_file_returns_config_parse_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad.toml");
        std::fs::write(&path, "invalid toml {{{{").unwrap();
        let result = ServerConfig::load(path.to_str().unwrap());
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            matches!(err, NetcidrError::ConfigParse(_)),
            "expected ConfigParse error, got: {err:?}"
        );
    }

    #[test]
    fn test_load_valid_toml_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("good.toml");
        std::fs::write(&path, "max_batch_size = 42\ntimeout_seconds = 5\n").unwrap();
        let config = ServerConfig::load(path.to_str().unwrap()).unwrap();
        assert_eq!(config.max_batch_size, 42);
        assert_eq!(config.timeout_seconds, 5);
    }

    #[test]
    fn test_load_invalid_bounds_returns_invalid_input() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad-bounds.toml");
        std::fs::write(&path, "timeout_seconds = 0\n").unwrap();
        let result = ServerConfig::load(path.to_str().unwrap());
        assert!(matches!(result, Err(NetcidrError::InvalidInput(_))));
    }

    #[test]
    fn test_merge_overrides_none_values_unchanged() {
        let mut config = ServerConfig::default();
        let original_batch = config.max_batch_size;
        let original_timeout = config.timeout_seconds;
        config.merge_cli_overrides(&CliOverrides::default());
        assert_eq!(config.max_batch_size, original_batch);
        assert_eq!(config.timeout_seconds, original_timeout);
        assert!(!config.enable_swagger);
        assert!(!config.ipam_enabled);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_merge_overrides_ipam_fields() {
        let mut config = ServerConfig::default();
        config.merge_cli_overrides(&CliOverrides {
            ipam_enabled: true,
            ipam_backend: Some("postgres".to_string()),
            ipam_db: Some("/tmp/test.db".to_string()),
            ipam_db_url: Some("postgresql://localhost/test".to_string()),
            ..Default::default()
        });
        assert!(config.ipam_enabled);
        assert_eq!(config.ipam_backend, "postgres");
        assert_eq!(config.ipam_db, Some("/tmp/test.db".to_string()));
        assert_eq!(
            config.ipam_db_url,
            Some("postgresql://localhost/test".to_string())
        );
        assert!(config.validate().is_ok());
    }
}
