use crate::error::{NetcidrError, Result};
use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
#[serde(default)]
pub struct ServerConfig {
    /// Maximum CIDRs in a single batch request
    pub max_batch_size: usize,
    /// Maximum CIDRs generated by from-range
    pub max_generated_cidrs: usize,
    /// Maximum input CIDRs for summarize
    pub max_summarize_inputs: usize,
    /// Maximum request body size in bytes
    pub max_body_size: usize,
    /// Rate limit: sustained requests per second
    pub rate_limit_per_second: u64,
    /// Rate limit: burst size
    pub rate_limit_burst: u32,
    /// Request timeout in seconds
    pub timeout_seconds: u64,
    /// Enable Swagger UI
    pub enable_swagger: bool,
    /// Enable IPAM API routes
    pub ipam_enabled: bool,
    /// IPAM storage backend ("sqlite" or "postgres")
    pub ipam_backend: String,
    /// IPAM database path (SQLite)
    pub ipam_db: Option<String>,
    /// IPAM database URL (PostgreSQL)
    pub ipam_db_url: Option<String>,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            max_batch_size: 10_000,
            max_generated_cidrs: 1_000_000,
            max_summarize_inputs: 10_000,
            max_body_size: 1_048_576, // 1 MB
            rate_limit_per_second: 20,
            rate_limit_burst: 50,
            timeout_seconds: 30,
            enable_swagger: false,
            ipam_enabled: false,
            ipam_backend: "sqlite".to_string(),
            ipam_db: None,
            ipam_db_url: None,
        }
    }
}

#[derive(Debug, Default)]
pub struct CliOverrides {
    pub enable_swagger: bool,
    pub max_batch_size: Option<usize>,
    pub max_range_cidrs: Option<usize>,
    pub max_summarize_inputs: Option<usize>,
    pub max_body_size: Option<usize>,
    pub rate_limit_per_second: Option<u64>,
    pub rate_limit_burst: Option<u32>,
    pub timeout: Option<u64>,
    pub ipam_enabled: bool,
    pub ipam_backend: Option<String>,
    pub ipam_db: Option<String>,
    pub ipam_db_url: Option<String>,
}

impl ServerConfig {
    pub fn load(path: &str) -> Result<Self> {
        // nosemgrep: rust.actix.path-traversal.tainted-path.tainted-path — CLI-only startup config, not reachable from HTTP input
        let contents = std::fs::read_to_string(path)?;
        let config: ServerConfig =
            toml::from_str(&contents).map_err(|e| NetcidrError::ConfigParse(e.to_string()))?;
        Ok(config)
    }

    pub fn merge_cli_overrides(&mut self, overrides: &CliOverrides) {
        if overrides.enable_swagger {
            self.enable_swagger = true;
        }
        if let Some(v) = overrides.max_batch_size {
            self.max_batch_size = v;
        }
        if let Some(v) = overrides.max_range_cidrs {
            self.max_generated_cidrs = v;
        }
        if let Some(v) = overrides.max_summarize_inputs {
            self.max_summarize_inputs = v;
        }
        if let Some(v) = overrides.max_body_size {
            self.max_body_size = v;
        }
        if let Some(v) = overrides.rate_limit_per_second {
            self.rate_limit_per_second = v;
        }
        if let Some(v) = overrides.rate_limit_burst {
            self.rate_limit_burst = v;
        }
        if let Some(v) = overrides.timeout {
            self.timeout_seconds = v;
        }
        if overrides.ipam_enabled {
            self.ipam_enabled = true;
        }
        if let Some(ref v) = overrides.ipam_backend {
            self.ipam_backend = v.clone();
        }
        if overrides.ipam_db.is_some() {
            self.ipam_db.clone_from(&overrides.ipam_db);
        }
        if overrides.ipam_db_url.is_some() {
            self.ipam_db_url.clone_from(&overrides.ipam_db_url);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = ServerConfig::default();
        assert_eq!(config.max_batch_size, 10_000);
        assert_eq!(config.max_generated_cidrs, 1_000_000);
        assert_eq!(config.max_summarize_inputs, 10_000);
        assert_eq!(config.max_body_size, 1_048_576);
        assert_eq!(config.rate_limit_per_second, 20);
        assert_eq!(config.rate_limit_burst, 50);
        assert_eq!(config.timeout_seconds, 30);
        assert!(!config.enable_swagger);
    }

    #[test]
    fn test_merge_cli_overrides() {
        let mut config = ServerConfig::default();
        config.merge_cli_overrides(&CliOverrides {
            enable_swagger: true,
            max_batch_size: Some(500),
            timeout: Some(60),
            ..Default::default()
        });
        assert!(config.enable_swagger);
        assert_eq!(config.max_batch_size, 500);
        assert_eq!(config.max_generated_cidrs, 1_000_000); // unchanged
        assert_eq!(config.timeout_seconds, 60);
    }

    #[test]
    fn test_toml_deserialization() {
        let toml_str = r#"
            max_batch_size = 500
            enable_swagger = true
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert_eq!(config.max_batch_size, 500);
        assert!(config.enable_swagger);
        // defaults for unspecified fields
        assert_eq!(config.max_generated_cidrs, 1_000_000);
    }

    #[test]
    fn test_invalid_toml_syntax_returns_config_parse_error() {
        let bad_toml = r#"max_batch_size = "not a number"#; // unclosed quote
        let result = toml::from_str::<ServerConfig>(bad_toml);
        assert!(result.is_err());
    }

    #[test]
    fn test_malformed_toml_missing_value() {
        let bad_toml = "max_batch_size = ";
        let result = toml::from_str::<ServerConfig>(bad_toml);
        assert!(result.is_err());
    }

    #[test]
    fn test_wrong_type_for_field() {
        let bad_toml = r#"max_batch_size = "hello""#;
        let result = toml::from_str::<ServerConfig>(bad_toml);
        assert!(result.is_err(), "string value for usize field should fail");
    }

    #[test]
    fn test_negative_value_for_unsigned_field() {
        let bad_toml = "timeout_seconds = -1";
        let result = toml::from_str::<ServerConfig>(bad_toml);
        assert!(result.is_err(), "negative value for u64 field should fail");
    }

    #[test]
    fn test_unknown_fields_are_accepted() {
        // serde(default) without deny_unknown_fields silently ignores unknown keys
        let toml_str = r#"
            max_batch_size = 42
            totally_fake_field = "hello"
            another_unknown = 999
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert_eq!(config.max_batch_size, 42);
        // other fields get defaults
        assert_eq!(config.timeout_seconds, 30);
    }

    #[test]
    fn test_partial_config_fills_defaults() {
        let toml_str = r#"
            enable_swagger = true
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert!(config.enable_swagger);
        assert_eq!(config.max_batch_size, 10_000);
        assert_eq!(config.max_generated_cidrs, 1_000_000);
        assert_eq!(config.max_summarize_inputs, 10_000);
        assert_eq!(config.max_body_size, 1_048_576);
        assert_eq!(config.rate_limit_per_second, 20);
        assert_eq!(config.rate_limit_burst, 50);
        assert_eq!(config.timeout_seconds, 30);
        assert!(!config.ipam_enabled);
        assert_eq!(config.ipam_backend, "sqlite");
        assert!(config.ipam_db.is_none());
        assert!(config.ipam_db_url.is_none());
    }

    #[test]
    fn test_empty_toml_yields_all_defaults() {
        let config: ServerConfig = toml::from_str("").unwrap();
        let defaults = ServerConfig::default();
        assert_eq!(config.max_batch_size, defaults.max_batch_size);
        assert_eq!(config.timeout_seconds, defaults.timeout_seconds);
        assert_eq!(config.enable_swagger, defaults.enable_swagger);
        assert_eq!(config.ipam_backend, defaults.ipam_backend);
    }

    #[test]
    fn test_boundary_values_zero() {
        let toml_str = r#"
            max_batch_size = 0
            timeout_seconds = 0
            rate_limit_per_second = 0
            rate_limit_burst = 0
            max_body_size = 0
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert_eq!(config.max_batch_size, 0);
        assert_eq!(config.timeout_seconds, 0);
        assert_eq!(config.rate_limit_per_second, 0);
        assert_eq!(config.rate_limit_burst, 0);
        assert_eq!(config.max_body_size, 0);
    }

    #[test]
    fn test_boundary_value_large_numbers() {
        let toml_str = r#"
            max_batch_size = 18446744073709551615
            timeout_seconds = 18446744073709551615
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert_eq!(config.max_batch_size, usize::MAX);
        assert_eq!(config.timeout_seconds, u64::MAX);
    }

    #[test]
    fn test_load_nonexistent_file_returns_io_error() {
        let result = ServerConfig::load("/tmp/nonexistent_netcidr_config_test.toml");
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            matches!(err, NetcidrError::Io(_)),
            "expected Io error, got: {err:?}"
        );
    }

    #[test]
    fn test_load_invalid_toml_file_returns_config_parse_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad.toml");
        std::fs::write(&path, "invalid toml {{{{").unwrap();
        let result = ServerConfig::load(path.to_str().unwrap());
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            matches!(err, NetcidrError::ConfigParse(_)),
            "expected ConfigParse error, got: {err:?}"
        );
    }

    #[test]
    fn test_load_valid_toml_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("good.toml");
        std::fs::write(&path, "max_batch_size = 42\ntimeout_seconds = 5\n").unwrap();
        let config = ServerConfig::load(path.to_str().unwrap()).unwrap();
        assert_eq!(config.max_batch_size, 42);
        assert_eq!(config.timeout_seconds, 5);
    }

    #[test]
    fn test_merge_overrides_none_values_unchanged() {
        let mut config = ServerConfig::default();
        let original_batch = config.max_batch_size;
        let original_timeout = config.timeout_seconds;
        config.merge_cli_overrides(&CliOverrides::default());
        assert_eq!(config.max_batch_size, original_batch);
        assert_eq!(config.timeout_seconds, original_timeout);
        assert!(!config.enable_swagger);
        assert!(!config.ipam_enabled);
    }

    #[test]
    fn test_merge_overrides_ipam_fields() {
        let mut config = ServerConfig::default();
        config.merge_cli_overrides(&CliOverrides {
            ipam_enabled: true,
            ipam_backend: Some("postgres".to_string()),
            ipam_db: Some("/tmp/test.db".to_string()),
            ipam_db_url: Some("postgresql://localhost/test".to_string()),
            ..Default::default()
        });
        assert!(config.ipam_enabled);
        assert_eq!(config.ipam_backend, "postgres");
        assert_eq!(config.ipam_db, Some("/tmp/test.db".to_string()));
        assert_eq!(
            config.ipam_db_url,
            Some("postgresql://localhost/test".to_string())
        );
    }
}
