use crate::error::{NetcidrError, Result};
use serde::Deserialize;
use std::net::IpAddr;

const MAX_BATCH_SIZE_LIMIT: usize = 100_000;
const MAX_GENERATED_CIDRS_LIMIT: usize = 1_000_000;
const MAX_SUMMARIZE_INPUTS_LIMIT: usize = 100_000;
const MAX_BODY_SIZE_LIMIT: usize = 10_485_760; // 10 MiB
const MAX_RATE_LIMIT_PER_SECOND: u64 = 10_000;
const MAX_RATE_LIMIT_BURST: u32 = 100_000;
const MAX_TIMEOUT_SECONDS: u64 = 300;
const AUTH_TOKEN_ENV: &str = "NETCIDR_API_TOKEN";
const OIDC_AUDIENCE_ENV: &str = "NETCIDR_OIDC_AUDIENCE";
const OIDC_CLI_CLIENT_ID_ENV: &str = "NETCIDR_OIDC_CLI_CLIENT_ID";
const OIDC_CLI_CLIENT_SECRET_ENV: &str = "NETCIDR_OIDC_CLI_CLIENT_SECRET";
const OIDC_ALLOWED_EMAILS_ENV: &str = "NETCIDR_OIDC_ALLOWED_EMAILS";
const ADMIN_EMAILS_ENV: &str = "NETCIDR_ADMIN_EMAILS";
const ALLOCATOR_EMAILS_ENV: &str = "NETCIDR_ALLOCATOR_EMAILS";
const READER_EMAILS_ENV: &str = "NETCIDR_READER_EMAILS";
const ALLOWLIST_MODE_ENV: &str = "NETCIDR_ALLOWLIST_MODE";

/// Whether sign-in is restricted to the users directory (ADR-0006).
///
/// `Closed`: only emails with an *active* `users` row may authenticate.
/// `Open`: any verified principal is admitted (role defaults to Reader;
/// a disabled directory row still denies).
///
/// When unset (`NETCIDR_ALLOWLIST_MODE` / `allowlist_mode` absent), the
/// mode derives from `NETCIDR_OIDC_ALLOWED_EMAILS`: non-empty → closed,
/// empty → open — the pre-flag behavior. Setting it explicitly lets a
/// deployment drop the email env vars entirely once the one-shot seed
/// has run, without silently flipping open.
#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum AllowlistMode {
    Open,
    Closed,
}

impl std::str::FromStr for AllowlistMode {
    type Err = NetcidrError;

    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s.trim().to_ascii_lowercase().as_str() {
            "open" => Ok(AllowlistMode::Open),
            "closed" => Ok(AllowlistMode::Closed),
            other => Err(NetcidrError::InvalidInput(format!(
                "invalid allowlist mode {other:?}: expected open|closed"
            ))),
        }
    }
}

#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum AuthMode {
    /// No application-layer authentication. Only safe for loopback/local use.
    #[default]
    None,
    /// Static bearer-token authentication for service-to-service/API usage.
    Bearer,
    /// OIDC/JWT authentication. Validates Google OIDC ID tokens from
    /// `Authorization: Bearer`; deployment-environment-agnostic.
    Oidc,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ServerConfig {
    /// Maximum CIDRs in a single batch request
    pub max_batch_size: usize,
    /// Maximum CIDRs generated by from-range
    pub max_generated_cidrs: usize,
    /// Maximum input CIDRs for summarize
    pub max_summarize_inputs: usize,
    /// Maximum request body size in bytes
    pub max_body_size: usize,
    /// Rate limit: sustained requests per second
    pub rate_limit_per_second: u64,
    /// Rate limit: burst size
    pub rate_limit_burst: u32,
    /// Request timeout in seconds
    pub timeout_seconds: u64,
    /// Enable Swagger UI
    pub enable_swagger: bool,
    /// Enable IPAM API routes
    pub ipam_enabled: bool,
    /// IPAM storage backend ("sqlite" or "postgres")
    pub ipam_backend: String,
    /// IPAM database path (SQLite)
    pub ipam_db: Option<String>,
    /// IPAM database URL (PostgreSQL)
    pub ipam_db_url: Option<String>,
    /// Authentication mode: none, bearer, or oidc.
    pub auth_mode: AuthMode,
    /// Bearer token for HTTP API authentication. Prefer NETCIDR_API_TOKEN in production.
    pub auth_token: Option<String>,
    /// Expected OIDC audience. Prefer NETCIDR_OIDC_AUDIENCE in production.
    pub oidc_audience: Option<String>,
    /// OAuth client ID of type "Desktop app" used by `netcidr login`.
    /// Advertised on `/features` so the CLI needs no local config.
    /// Prefer NETCIDR_OIDC_CLI_CLIENT_ID in production.
    #[serde(default)]
    pub oidc_cli_client_id: Option<String>,
    /// Matching client secret. Non-confidential by design — an installed
    /// app cannot keep a secret (RFC 8252 s8.5); PKCE is what secures the
    /// exchange. Served publicly on `/features` on purpose.
    /// Prefer NETCIDR_OIDC_CLI_CLIENT_SECRET in production.
    #[serde(default)]
    pub oidc_cli_client_secret: Option<String>,
    /// Allowlist of email addresses authorized to call protected endpoints.
    /// Post-seed this list is inert (the users directory is the source of
    /// truth) except that, when `allowlist_mode` is unset, its
    /// non-emptiness selects closed mode.
    /// Prefer NETCIDR_OIDC_ALLOWED_EMAILS (comma-separated) in production.
    #[serde(default)]
    pub oidc_allowed_emails: Vec<String>,
    /// Explicit allowlist mode ("open" | "closed"). Unset = derive from
    /// `oidc_allowed_emails` non-emptiness (pre-flag behavior). Prefer
    /// NETCIDR_ALLOWLIST_MODE in production. See [`AllowlistMode`].
    #[serde(default)]
    pub allowlist_mode: Option<AllowlistMode>,
    /// Email addresses with administrative access (e.g. allowlist viewer).
    /// Prefer NETCIDR_ADMIN_EMAILS (comma-separated) in production.
    #[serde(default)]
    pub admin_emails: Vec<String>,
    /// Email addresses granted the `allocator` role (read + allocate/release/update).
    /// Empty means no users default to allocator. See ADR-0002 for the role model
    /// and the back-compat default-admin policy.
    /// Prefer NETCIDR_ALLOCATOR_EMAILS (comma-separated) in production.
    #[serde(default)]
    pub oidc_allocator_emails: Vec<String>,
    /// Email addresses granted the `reader` role (read-only).
    /// Empty means no users default to reader.
    /// Prefer NETCIDR_READER_EMAILS (comma-separated) in production.
    #[serde(default)]
    pub oidc_reader_emails: Vec<String>,
    /// Allow binding the HTTP API to a non-loopback address.
    pub allow_public_bind: bool,
    /// Require authentication when binding the HTTP API to a non-loopback address.
    pub require_auth_for_public_bind: bool,
    /// Maximum number of active (non-revoked, non-expired) PATs per tenant.
    /// Callers that exceed this cap receive 429 and must revoke a token first.
    pub max_pats_per_tenant: u32,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            max_batch_size: 10_000,
            max_generated_cidrs: 1_000_000,
            max_summarize_inputs: 10_000,
            max_body_size: 1_048_576, // 1 MB
            rate_limit_per_second: 20,
            rate_limit_burst: 50,
            timeout_seconds: 30,
            enable_swagger: false,
            ipam_enabled: false,
            ipam_backend: "sqlite".to_string(),
            ipam_db: None,
            ipam_db_url: None,
            auth_mode: AuthMode::None,
            auth_token: None,
            oidc_audience: None,
            oidc_cli_client_id: None,
            oidc_cli_client_secret: None,
            oidc_allowed_emails: Vec::new(),
            allowlist_mode: None,
            admin_emails: Vec::new(),
            oidc_allocator_emails: Vec::new(),
            oidc_reader_emails: Vec::new(),
            allow_public_bind: false,
            require_auth_for_public_bind: true,
            max_pats_per_tenant: 25,
        }
    }
}

#[derive(Debug, Default)]
pub struct CliOverrides {
    pub enable_swagger: bool,
    pub max_batch_size: Option<usize>,
    pub max_range_cidrs: Option<usize>,
    pub max_summarize_inputs: Option<usize>,
    pub max_body_size: Option<usize>,
    pub rate_limit_per_second: Option<u64>,
    pub rate_limit_burst: Option<u32>,
    pub timeout: Option<u64>,
    pub ipam_enabled: bool,
    pub ipam_backend: Option<String>,
    pub ipam_db: Option<String>,
    pub ipam_db_url: Option<String>,
}

impl ServerConfig {
    pub fn load(path: &str) -> Result<Self> {
        // nosemgrep: rust.actix.path-traversal.tainted-path.tainted-path — CLI-only startup config, not reachable from HTTP input
        let contents = std::fs::read_to_string(path)?;
        let config: ServerConfig =
            toml::from_str(&contents).map_err(|e| NetcidrError::ConfigParse(e.to_string()))?;
        config.validate()?;
        Ok(config)
    }

    pub fn merge_cli_overrides(&mut self, overrides: &CliOverrides) {
        if overrides.enable_swagger {
            self.enable_swagger = true;
        }
        if let Some(v) = overrides.max_batch_size {
            self.max_batch_size = v;
        }
        if let Some(v) = overrides.max_range_cidrs {
            self.max_generated_cidrs = v;
        }
        if let Some(v) = overrides.max_summarize_inputs {
            self.max_summarize_inputs = v;
        }
        if let Some(v) = overrides.max_body_size {
            self.max_body_size = v;
        }
        if let Some(v) = overrides.rate_limit_per_second {
            self.rate_limit_per_second = v;
        }
        if let Some(v) = overrides.rate_limit_burst {
            self.rate_limit_burst = v;
        }
        if let Some(v) = overrides.timeout {
            self.timeout_seconds = v;
        }
        if overrides.ipam_enabled {
            self.ipam_enabled = true;
        }
        if let Some(ref v) = overrides.ipam_backend {
            self.ipam_backend = v.clone();
        }
        if overrides.ipam_db.is_some() {
            self.ipam_db.clone_from(&overrides.ipam_db);
        }
        if overrides.ipam_db_url.is_some() {
            self.ipam_db_url.clone_from(&overrides.ipam_db_url);
        }
    }

    pub fn validate(&self) -> Result<()> {
        validate_range_usize(
            "max_batch_size",
            self.max_batch_size,
            1,
            MAX_BATCH_SIZE_LIMIT,
        )?;
        validate_range_usize(
            "max_generated_cidrs",
            self.max_generated_cidrs,
            1,
            MAX_GENERATED_CIDRS_LIMIT,
        )?;
        validate_range_usize(
            "max_summarize_inputs",
            self.max_summarize_inputs,
            1,
            MAX_SUMMARIZE_INPUTS_LIMIT,
        )?;
        validate_range_usize("max_body_size", self.max_body_size, 1, MAX_BODY_SIZE_LIMIT)?;
        validate_range_u64(
            "rate_limit_per_second",
            self.rate_limit_per_second,
            1,
            MAX_RATE_LIMIT_PER_SECOND,
        )?;
        validate_range_u32(
            "rate_limit_burst",
            self.rate_limit_burst,
            1,
            MAX_RATE_LIMIT_BURST,
        )?;
        validate_range_u64(
            "timeout_seconds",
            self.timeout_seconds,
            1,
            MAX_TIMEOUT_SECONDS,
        )?;

        if self
            .auth_token
            .as_ref()
            .is_some_and(|token| token.trim().is_empty())
        {
            return Err(NetcidrError::InvalidInput(
                "auth_token must not be empty".to_string(),
            ));
        }
        if self
            .oidc_audience
            .as_ref()
            .is_some_and(|audience| audience.trim().is_empty())
        {
            return Err(NetcidrError::InvalidInput(
                "oidc_audience must not be empty".to_string(),
            ));
        }
        // Surface an unparseable NETCIDR_ALLOWLIST_MODE at startup — a
        // security switch must not fall back silently.
        self.allowlist_mode()?;
        match self.auth_mode {
            AuthMode::None => {}
            AuthMode::Bearer => {
                if self.auth_token().is_none() {
                    return Err(NetcidrError::InvalidInput(format!(
                        "auth_mode='bearer' requires {AUTH_TOKEN_ENV} or auth_token"
                    )));
                }
            }
            AuthMode::Oidc => {
                if self.oidc_audience().is_none() {
                    return Err(NetcidrError::InvalidInput(format!(
                        "auth_mode='oidc' requires {OIDC_AUDIENCE_ENV} or oidc_audience"
                    )));
                }
            }
        }

        match self.ipam_backend.as_str() {
            "sqlite" | "postgres" => Ok(()),
            other => Err(NetcidrError::InvalidInput(format!(
                "ipam_backend must be 'sqlite' or 'postgres' (got '{other}')"
            ))),
        }
    }

    pub fn auth_token(&self) -> Option<String> {
        std::env::var(AUTH_TOKEN_ENV)
            .ok()
            .filter(|token| !token.trim().is_empty())
            .or_else(|| {
                self.auth_token
                    .clone()
                    .filter(|token| !token.trim().is_empty())
            })
    }

    pub fn oidc_audience(&self) -> Option<String> {
        std::env::var(OIDC_AUDIENCE_ENV)
            .ok()
            .filter(|audience| !audience.trim().is_empty())
            .or_else(|| {
                self.oidc_audience
                    .clone()
                    .filter(|audience| !audience.trim().is_empty())
            })
    }

    pub fn oidc_cli_client_id(&self) -> Option<String> {
        resolve_optional(OIDC_CLI_CLIENT_ID_ENV, self.oidc_cli_client_id.as_deref())
    }

    pub fn oidc_cli_client_secret(&self) -> Option<String> {
        resolve_optional(
            OIDC_CLI_CLIENT_SECRET_ENV,
            self.oidc_cli_client_secret.as_deref(),
        )
    }

    pub fn auth_configured(&self) -> bool {
        match self.auth_mode {
            AuthMode::None => false,
            AuthMode::Bearer => self.auth_token().is_some(),
            AuthMode::Oidc => self.oidc_audience().is_some(),
        }
    }

    pub fn oidc_allowed_emails(&self) -> Vec<String> {
        resolve_email_list(OIDC_ALLOWED_EMAILS_ENV, &self.oidc_allowed_emails)
    }

    /// Resolve the effective allowlist mode: env var > config file >
    /// derived from allowlist non-emptiness. Fails on an unparseable env
    /// value (a security switch must not fall back silently).
    pub fn allowlist_mode(&self) -> Result<AllowlistMode> {
        if let Ok(raw) = std::env::var(ALLOWLIST_MODE_ENV)
            && !raw.trim().is_empty()
        {
            return raw.parse::<AllowlistMode>();
        }
        if let Some(mode) = self.allowlist_mode {
            return Ok(mode);
        }
        Ok(if self.oidc_allowed_emails().is_empty() {
            AllowlistMode::Open
        } else {
            AllowlistMode::Closed
        })
    }

    pub fn admin_emails(&self) -> Vec<String> {
        resolve_email_list(ADMIN_EMAILS_ENV, &self.admin_emails)
    }

    pub fn allocator_emails(&self) -> Vec<String> {
        resolve_email_list(ALLOCATOR_EMAILS_ENV, &self.oidc_allocator_emails)
    }

    pub fn reader_emails(&self) -> Vec<String> {
        resolve_email_list(READER_EMAILS_ENV, &self.oidc_reader_emails)
    }

    pub fn auth_config(&self) -> crate::auth::AuthConfig {
        crate::auth::AuthConfig::new(
            self.auth_mode,
            self.auth_token(),
            self.oidc_audience(),
            self.oidc_allowed_emails(),
        )
        .with_admin_emails(self.admin_emails())
        .with_allocator_emails(self.allocator_emails())
        .with_reader_emails(self.reader_emails())
        // Invalid mode values are rejected by validate() at startup; the
        // unwrap here fails *closed* as defense in depth.
        .with_allowlist_mode(self.allowlist_mode().unwrap_or(AllowlistMode::Closed))
    }

    pub fn validate_deployment(&self, bind_address: &str) -> Result<()> {
        self.validate()?;

        let is_loopback = is_loopback_bind_address(bind_address)?;
        if !is_loopback {
            if !self.allow_public_bind {
                return Err(NetcidrError::InvalidInput(format!(
                    "refusing to bind to non-loopback address '{bind_address}' unless allow_public_bind=true"
                )));
            }
            if self.require_auth_for_public_bind && !self.auth_configured() {
                return Err(NetcidrError::InvalidInput(
                    "refusing to bind to non-loopback address without authentication; set auth_mode to 'bearer' or 'oidc' and configure its required settings"
                        .to_string(),
                ));
            }
        }

        if self.ipam_enabled && !self.auth_configured() {
            return Err(NetcidrError::InvalidInput(
                "IPAM API requires auth_mode='bearer' or auth_mode='oidc' with required settings"
                    .to_string(),
            ));
        }

        Ok(())
    }
}

/// Env-var-wins resolution for a single optional string setting, with
/// blank values treated as unset. Mirrors the shape of `auth_token()` and
/// `oidc_audience()` so the precedence rule stays uniform.
fn resolve_optional(env_var: &str, fallback: Option<&str>) -> Option<String> {
    std::env::var(env_var)
        .ok()
        .filter(|value| !value.trim().is_empty())
        .or_else(|| {
            fallback
                .map(str::to_string)
                .filter(|value| !value.trim().is_empty())
        })
}

/// Resolve a comma-separated email list with env-var taking precedence
/// over the config-file field, then lower-cases and de-blanks the result.
/// Shared by `oidc_allowed_emails`, `admin_emails`, `allocator_emails`, and
/// `reader_emails` so the parsing rules can't drift.
fn resolve_email_list(env_var: &str, fallback: &[String]) -> Vec<String> {
    let from_env = std::env::var(env_var).ok().filter(|s| !s.trim().is_empty());
    let raw: Vec<String> = match from_env {
        Some(v) => v
            .split(',')
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect(),
        None => fallback
            .iter()
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect(),
    };
    raw.into_iter().map(|s| s.to_ascii_lowercase()).collect()
}

pub(crate) fn is_loopback_bind_address(bind_address: &str) -> Result<bool> {
    let trimmed = bind_address.trim();
    let host = trimmed
        .strip_prefix('[')
        .and_then(|s| s.strip_suffix(']'))
        .unwrap_or(trimmed);

    let ip: IpAddr = host.parse().map_err(|_| {
        NetcidrError::InvalidInput(format!("invalid bind address '{bind_address}'"))
    })?;
    Ok(ip.is_loopback())
}

fn validate_range_usize(name: &str, value: usize, min: usize, max: usize) -> Result<()> {
    if value < min || value > max {
        return Err(NetcidrError::InvalidInput(format!(
            "{name} must be between {min} and {max} (got {value})"
        )));
    }
    Ok(())
}

fn validate_range_u64(name: &str, value: u64, min: u64, max: u64) -> Result<()> {
    if value < min || value > max {
        return Err(NetcidrError::InvalidInput(format!(
            "{name} must be between {min} and {max} (got {value})"
        )));
    }
    Ok(())
}

fn validate_range_u32(name: &str, value: u32, min: u32, max: u32) -> Result<()> {
    if value < min || value > max {
        return Err(NetcidrError::InvalidInput(format!(
            "{name} must be between {min} and {max} (got {value})"
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn bearer_config() -> ServerConfig {
        ServerConfig {
            auth_mode: AuthMode::Bearer,
            auth_token: Some("test-token".to_string()),
            ..Default::default()
        }
    }

    fn oidc_config() -> ServerConfig {
        ServerConfig {
            auth_mode: AuthMode::Oidc,
            oidc_audience: Some("/projects/123/global/backendServices/456".to_string()),
            ..Default::default()
        }
    }

    #[test]
    fn allowlist_mode_derives_from_list_and_config_pins_it() {
        // NOTE: the env-var override path (NETCIDR_ALLOWLIST_MODE) is not
        // exercised here — mutating process env in tests requires unsafe
        // in edition 2024, which this codebase forbids. The env branch is
        // a two-line delegation to the same FromStr tested below.

        // Derived: empty list → open; populated → closed.
        let open = oidc_config();
        assert_eq!(open.allowlist_mode().unwrap(), AllowlistMode::Open);
        let closed = ServerConfig {
            oidc_allowed_emails: vec!["a@example.com".to_string()],
            ..oidc_config()
        };
        assert_eq!(closed.allowlist_mode().unwrap(), AllowlistMode::Closed);

        // Explicit config pins the mode regardless of the list.
        let pinned_closed = ServerConfig {
            allowlist_mode: Some(AllowlistMode::Closed),
            ..oidc_config()
        };
        assert_eq!(
            pinned_closed.allowlist_mode().unwrap(),
            AllowlistMode::Closed
        );
        let pinned_open = ServerConfig {
            oidc_allowed_emails: vec!["a@example.com".to_string()],
            allowlist_mode: Some(AllowlistMode::Open),
            ..oidc_config()
        };
        assert_eq!(pinned_open.allowlist_mode().unwrap(), AllowlistMode::Open);

        // FromStr: the parser behind the env override.
        assert_eq!(
            "closed".parse::<AllowlistMode>().unwrap(),
            AllowlistMode::Closed
        );
        assert_eq!(
            "OPEN".parse::<AllowlistMode>().unwrap(),
            AllowlistMode::Open
        );
        assert!("locked".parse::<AllowlistMode>().is_err());

        // TOML round trip.
        let cfg: ServerConfig = toml::from_str("allowlist_mode = \"closed\"").expect("toml parse");
        assert_eq!(cfg.allowlist_mode, Some(AllowlistMode::Closed));
    }

    #[test]
    fn test_default_config() {
        let config = ServerConfig::default();
        assert_eq!(config.max_batch_size, 10_000);
        assert_eq!(config.auth_mode, AuthMode::None);
        assert!(!config.allow_public_bind);
        assert!(config.require_auth_for_public_bind);
        assert!(config.validate().is_ok());
        assert!(!config.auth_configured());
    }

    #[test]
    fn test_toml_deserialization_for_bearer() {
        let toml_str = r#"
            max_batch_size = 500
            enable_swagger = true
            auth_mode = "bearer"
            auth_token = "test-token"
            allow_public_bind = true
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert_eq!(config.max_batch_size, 500);
        assert!(config.enable_swagger);
        assert_eq!(config.auth_mode, AuthMode::Bearer);
        assert_eq!(config.auth_token.as_deref(), Some("test-token"));
        assert!(config.allow_public_bind);
        assert!(config.validate().is_ok());
        assert!(config.auth_configured());
    }

    #[test]
    fn test_toml_deserialization_for_oidc() {
        let toml_str = r#"
            auth_mode = "oidc"
            oidc_audience = "/projects/123/global/backendServices/456"
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert_eq!(config.auth_mode, AuthMode::Oidc);
        assert_eq!(
            config.oidc_audience.as_deref(),
            Some("/projects/123/global/backendServices/456")
        );
        assert!(config.validate().is_ok());
        assert!(config.auth_configured());
    }

    #[test]
    fn test_unknown_fields_are_rejected() {
        let toml_str = r#"
            max_batch_size = 42
            totally_fake_field = "hello"
        "#;
        let result = toml::from_str::<ServerConfig>(toml_str);
        assert!(result.is_err(), "unknown config fields should fail closed");
    }

    #[test]
    fn test_invalid_auth_mode_is_rejected() {
        let toml_str = r#"auth_mode = "google""#;
        let result = toml::from_str::<ServerConfig>(toml_str);
        assert!(result.is_err());
    }

    #[test]
    fn test_bearer_mode_requires_token() {
        let config = ServerConfig {
            auth_mode: AuthMode::Bearer,
            ..Default::default()
        };
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_oidc_mode_requires_audience() {
        let config = ServerConfig {
            auth_mode: AuthMode::Oidc,
            ..Default::default()
        };
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_empty_auth_fields_are_rejected() {
        let config = ServerConfig {
            auth_token: Some("   ".to_string()),
            ..Default::default()
        };
        assert!(config.validate().is_err());

        let config = ServerConfig {
            oidc_audience: Some("   ".to_string()),
            ..Default::default()
        };
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_config_bounds_are_rejected() {
        let toml_str = r#"
            max_batch_size = 0
            timeout_seconds = 0
            rate_limit_per_second = 0
            rate_limit_burst = 0
            max_body_size = 0
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert!(config.validate().is_err());

        let toml_str = r#"
            max_batch_size = 18446744073709551615
            timeout_seconds = 18446744073709551615
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_invalid_ipam_backend_is_rejected() {
        let config = ServerConfig {
            ipam_backend: "mysql".to_string(),
            ..Default::default()
        };
        assert!(config.validate().is_err());
    }

    #[test]
    fn test_validate_deployment_allows_loopback_without_auth() {
        let config = ServerConfig::default();
        assert!(config.validate_deployment("127.0.0.1").is_ok());
        assert!(config.validate_deployment("::1").is_ok());
        assert!(config.validate_deployment("[::1]").is_ok());
    }

    #[test]
    fn test_validate_deployment_rejects_public_bind_without_opt_in() {
        let config = bearer_config();
        assert!(config.validate_deployment("0.0.0.0").is_err());
    }

    #[test]
    fn test_validate_deployment_rejects_public_bind_without_auth() {
        let config = ServerConfig {
            allow_public_bind: true,
            ..Default::default()
        };
        assert!(config.validate_deployment("0.0.0.0").is_err());
    }

    #[test]
    fn test_validate_deployment_allows_public_bind_with_bearer_auth_and_opt_in() {
        let config = ServerConfig {
            allow_public_bind: true,
            ..bearer_config()
        };
        assert!(config.validate_deployment("0.0.0.0").is_ok());
    }

    #[test]
    fn test_validate_deployment_allows_public_bind_with_oidc_and_opt_in() {
        let config = ServerConfig {
            allow_public_bind: true,
            ..oidc_config()
        };
        assert!(config.validate_deployment("0.0.0.0").is_ok());
    }

    #[test]
    fn test_validate_deployment_rejects_ipam_without_auth() {
        let config = ServerConfig {
            ipam_enabled: true,
            ..Default::default()
        };
        assert!(config.validate_deployment("127.0.0.1").is_err());
    }

    #[test]
    fn test_validate_deployment_allows_ipam_with_oidc() {
        let config = ServerConfig {
            ipam_enabled: true,
            ..oidc_config()
        };
        assert!(config.validate_deployment("127.0.0.1").is_ok());
    }

    #[test]
    fn test_load_valid_toml_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("good.toml");
        std::fs::write(&path, "max_batch_size = 42\ntimeout_seconds = 5\n").unwrap();
        let config = ServerConfig::load(path.to_str().unwrap()).unwrap();
        assert_eq!(config.max_batch_size, 42);
        assert_eq!(config.timeout_seconds, 5);
    }

    #[test]
    fn test_load_invalid_bounds_returns_invalid_input() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad-bounds.toml");
        std::fs::write(&path, "timeout_seconds = 0\n").unwrap();
        let result = ServerConfig::load(path.to_str().unwrap());
        assert!(matches!(result, Err(NetcidrError::InvalidInput(_))));
    }

    #[test]
    fn test_merge_overrides_ipam_fields() {
        let mut config = ServerConfig::default();
        config.merge_cli_overrides(&CliOverrides {
            ipam_enabled: true,
            ipam_backend: Some("postgres".to_string()),
            ipam_db: Some("/tmp/test.db".to_string()),
            ipam_db_url: Some("postgresql://localhost/test".to_string()),
            ..Default::default()
        });
        assert!(config.ipam_enabled);
        assert_eq!(config.ipam_backend, "postgres");
        assert_eq!(config.ipam_db, Some("/tmp/test.db".to_string()));
        assert_eq!(
            config.ipam_db_url,
            Some("postgresql://localhost/test".to_string())
        );
        // validate fails until an auth mode is configured because IPAM requires auth.
        assert!(config.validate_deployment("127.0.0.1").is_err());
    }
}
