name: cargo-deny

on:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
      - ".github/workflows/cargo-deny.yml"
  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
      - ".github/workflows/cargo-deny.yml"
  schedule:
    - cron: "0 7 * * 1"

permissions:
  contents: read

jobs:
  cargo-deny:
    name: cargo-deny ${{ matrix.checks }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        checks:
          - advisories
          - bans licenses sources
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: EmbarkStudios/cargo-deny-action@91bf2b620e09e18d6eb78b92e7861937469acedb # v2.0.17
        with:
          command: check ${{ matrix.checks }}
