name: cargo-deny

on:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
      - ".github/workflows/cargo-deny.yml"
  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
      - ".github/workflows/cargo-deny.yml"
  schedule:
    - cron: "0 7 * * 1"

permissions:
  contents: read

jobs:
  cargo-deny:
    name: cargo-deny ${{ matrix.checks }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        checks:
          - advisories
          - bans licenses sources
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: EmbarkStudios/cargo-deny-action@a531616d8ce3b9177443e48a1159bc945a099823 # v2.0.19
        with:
          command: check ${{ matrix.checks }}
